# -*- coding: utf-8 -*-
"""Python사칙연산.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Bk2kLO_xSp63S8fel9Fj7XeQae0RkVu

## 테스트입니다.

## 사칙연산
"""



print("Hello World")

print(1 + 1)

print(5 -2)

print(15 * 2)

print(10 /2)

print(int(10/ 2))

print(1.2 + 5.3)

print(3.5 - 5.0)

print(1.4 * 2)

print(5 / 2)

"""### 복합연산"""

2 + 3 * 4

3 / 2 * 4 - 5 / 2

10 / 5 + (5 -2) * 2

(5 * 4 - 15) + ((5 - 2) * (9 - 7))

"""### 타입함수"""

type(3)

type(3.0)

type(0.1)

type(-1)

type("Hello World")

type(1.2)

j = str(type(type(a)))
type(j)

2 ** 5

5 ** 2

2 ** (1 / 2)

12 // 5

13 % 5

"""### 과학적 표기법"""

3e8

int(3e8)

e3

1e3

int(1e3)

1e15

1e-4

"""앞에 0b를 붙이면 2진수로 표현 가능 ex)10001

진수 표현과 변환
출력 결과는 숫자가 아니라 __문자열__
출력 결과는 작은 따옴표__''__ 안에 있음
bin(), oct(),hex()는 출력할 때만 사용
"""

0b10001

0b11

0b10

0o21

0x11

## 16진수로 16 만들기 8진수로 16만들기
00010000  010000

0b00010000

0o20

bin(17)

0b11

int("0b10000", 2)

0x11

0b10 * 0o10 + 0x10 - 10

type(bool(a))

bool(a)

bool(0)

type(bool(0))

bool(type(0))

type(type(bool(a)))

type(str(type(bool(a))))

type(str)

type(int)

type(bool)

type(str(type(a)))

type(type(str))

print(bool(a))

print(bool(0))

print(bool(none))

print(bool(dkdk))

print(bool(a))

print(bool(bb))

print(bool('b'b))

print(bool('b'))

print(88)

print(bool(88))

print(bool(9.2))

a = 3
if bool(a) == 0:
    print("hh")
else: print('d')

True and False

True & Fasle

True or False

not False

type(true)

type(True)

A = 1
B = 0
print(bool(not A))

print(5 == 3)

print(0)

print(bool(0))

def mul(a, b):
    return a ** b

print(mul(2, 3))

print(1 > 0 and -2 < 0)

print(not(1>0 and -2 < 0))

/\ /\
~ \^~^/~~
   \\\\